image: gradle:jdk17

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:
  - build
  - test

build-step:
  stage: build
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - cache/caches/
      - cache/notifications/
      - cache/wrapper/
  script:
      - ./gradlew clean
      - ./gradlew --build-cache --gradle-user-home cache/ check

test-phase:
  stage: test
  script: ./gradlew check
